"""Python interface for the fpm-rs reconstruction and simulation core."""

from . import diagnostics
from . import datasets
from . import evaluation
from . import metrics
from . import plot
from ._core import (
    AdaptiveAlternatingProjection,
    Admm,
    AlternatingProjection,
    AcquisitionPlan,
    ArrayPose,
    BundleArray,
    BundleArrays,
    BundleArtifact,
    BundlePreviews,
    BundleTables,
    BundleVerificationResult,
    BenchmarkBundle,
    BenchmarkBundleTables,
    BenchmarkSuite,
    CameraModel,
    CalibrationConditioning,
    CalibrationLossHistoryEntry,
    CalibrationParameterHistoryEntry,
    CalibrationParameterSpec,
    CheckpointEvery,
    CsvLogger,
    DatasetError,
    Dataset,
    DatasetRegistry,
    DatasetRegistryEntry,
    DiagnosticRecorder,
    Epry,
    Fpie,
    FpmError,
    FpmIoError,
    FrameOutOfRangeError,
    GradientDescent,
    BoundedFiniteDifferenceOptimizer,
    BrightfieldCircleInitializer,
    BrightfieldCircleObservation,
    BrightfieldCircleOptions,
    IlluminationAcquisitionErrors,
    Illumination,
    IlluminationCalibration,
    IlluminationCalibrationState,
    IlluminationFrame,
    ImagePlaneModel,
    InitializationBundle,
    InitializationBundleArtifact,
    InitializationBundleVerificationResult,
    InvalidMeasurementsError,
    InvalidModelError,
    InvalidParameterError,
    InvalidShapeError,
    IterationCallback,
    KVectorList,
    DirectionList,
    PlanarLEDArray,
    PlanarArrayCalibrationParameters,
    PlanarArrayInitializationCallback,
    PlanarArrayInitializationDiagnostics,
    PlanarArrayInitializationFitRecord,
    PlanarArrayInitializationResult,
    PlanarArrayInitializationRuntime,
    PlanarArrayParameterValues,
    ResolvedFrame,
    ResolvedIllumination,
    ResolvedSources,
    LengthMismatchError,
    MeasurementStack,
    NumericalError,
    Mpie,
    Optics,
    ProgressLogger,
    PupilAberration,
    ReconstructionCheckpoint,
    ReconstructionProblem,
    ReconstructionResult,
    JointReconstruction,
    JointReconstructionResult,
    ResultBundle,
    RuntimeInfo,
    RotatingLEDArc,
    SourceCalibration,
    SourceContribution,
    SourceGeometry,
    SourcePositionList,
    SaveImageEvery,
    SavePupilEvery,
    SaveResidualsEvery,
    SerializationError,
    SimulationResult,
    SyntheticObject,
    StopOnPlateau,
    SphericalLEDArm,
    SphericalLEDArray,
    UnsupportedError,
    __version__,
    compile_camera_model,
    compile_model,
    open_dataset,
    read_bundle,
    read_benchmark_bundle,
    read_initialization_bundle,
    simulate,
    suggest_reconstruction_shape,
)

# Backwards-compatible alias; use ``fpm_rs.metrics.radial_fourier_spectrum``.
radial_fourier_spectrum = metrics.radial_fourier_spectrum

__all__ = [name for name in globals() if not name.startswith("_")]
