"""Python interface for the fpm-rs reconstruction and simulation core."""

from . import diagnostics
from . import datasets
from . import evaluation
from . import metrics
from . import plot
from ._core import (
    Admm,
    AlternatingProjection,
    AngleList,
    BundleArray,
    BundleArrays,
    BundleArtifact,
    BundlePreviews,
    BundleTables,
    BundleVerificationResult,
    BenchmarkBundle,
    BenchmarkBundleTables,
    BenchmarkSuite,
    CameraModel,
    CheckpointEvery,
    CodedIllumination,
    CsvLogger,
    DatasetError,
    Dataset,
    DatasetRegistry,
    DatasetRegistryEntry,
    DiagnosticRecorder,
    Epry,
    Fpie,
    FpmError,
    FpmIoError,
    FrameOutOfRangeError,
    GradientDescent,
    IlluminationAcquisitionErrors,
    ImagePlaneModel,
    InvalidMeasurementsError,
    InvalidModelError,
    InvalidParameterError,
    InvalidShapeError,
    IterationCallback,
    KVectorList,
    LEDArray,
    LEDSphere,
    LengthMismatchError,
    MeasurementStack,
    NumericalError,
    Optics,
    ProgressLogger,
    PupilAberration,
    ReconstructionCheckpoint,
    ReconstructionProblem,
    ReconstructionResult,
    ResultBundle,
    RuntimeInfo,
    RotatingLEDArc,
    SaveImageEvery,
    SavePupilEvery,
    SaveResidualsEvery,
    SerializationError,
    SimulationResult,
    SyntheticObject,
    StopOnPlateau,
    SphericalLEDArm,
    UnsupportedError,
    __version__,
    compile_camera_model,
    compile_model,
    open_dataset,
    read_bundle,
    read_benchmark_bundle,
    simulate,
    suggest_reconstruction_shape,
)

# Backwards-compatible alias; use ``fpm_rs.metrics.radial_fourier_spectrum``.
radial_fourier_spectrum = metrics.radial_fourier_spectrum

__all__ = [name for name in globals() if not name.startswith("_")]
