"""Python interface for the fpm-rs reconstruction and simulation core."""

from . import diagnostics
from . import plot
from ._core import (
    Admm,
    AlternatingProjection,
    AngleList,
    CameraModel,
    CheckpointEvery,
    CodedIllumination,
    CsvLogger,
    DatasetError,
    DiagnosticRecorder,
    Epry,
    Fpie,
    FpmError,
    FpmIoError,
    FrameOutOfRangeError,
    GradientDescent,
    IlluminationAcquisitionErrors,
    ImagePlaneModel,
    InvalidMeasurementsError,
    InvalidModelError,
    InvalidParameterError,
    InvalidShapeError,
    IterationCallback,
    KVectorList,
    LEDArray,
    LEDSphere,
    LengthMismatchError,
    MeasurementStack,
    NumericalError,
    Optics,
    ProgressLogger,
    PupilAberration,
    ReconstructionCheckpoint,
    ReconstructionProblem,
    ReconstructionResult,
    RuntimeInfo,
    RotatingLEDArc,
    SaveImageEvery,
    SavePupilEvery,
    SaveResidualsEvery,
    SerializationError,
    SimulationResult,
    SyntheticObject,
    StopOnPlateau,
    SphericalLEDArm,
    UnsupportedError,
    __version__,
    compile_camera_model,
    compile_model,
    simulate,
)

__all__ = [name for name in globals() if not name.startswith("_")]
